(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  $('#year').textContent=new Date().getFullYear();
  const themeToggle=$('.theme-toggle'), metaTheme=document.querySelector('meta[name="theme-color"]');
  function updateThemeAssets(light){const pairs={'projectw-logo.svg':'projectw-logo-light.svg','chargeguard-logo.svg':'chargeguard-logo-light.svg','qrcraft-logo.svg':'qrcraft-logo-light.svg','relayotp-logo.svg':'relayotp-logo-light.svg','projectw-lockup-asset.svg':'projectw-lockup-light.svg',
      
      'projectw-wordmark.svg':'projectw-wordmark-light.svg'};const rev=Object.fromEntries(Object.entries(pairs).map(([d,l])=>[l,d]));document.querySelectorAll('img').forEach(img=>{const src=img.getAttribute('src')||'',file=src.split('/').pop(),next=light?pairs[file]:rev[file];if(next)img.setAttribute('src',src.replace(file,next));});}function syncTheme(){const t=document.documentElement.dataset.theme||'dark', light=t==='light'; if(themeToggle){themeToggle.setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode');themeToggle.setAttribute('aria-pressed',String(light));$('.theme-text',themeToggle).textContent=light?'Light':'Dark';} if(metaTheme)metaTheme.setAttribute('content',light?'#f7f9ff':'#050713');updateThemeAssets(light);}
  syncTheme(); themeToggle?.addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';localStorage.setItem('projectw-theme',document.documentElement.dataset.theme);syncTheme();});
  $('.menu')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));
  const navDropTrigger = $('.nav-drop-trigger');
  navDropTrigger?.addEventListener('click', (e) => {
    if (window.matchMedia('(max-width: 980px)').matches) {
      e.preventDefault();
      const wrap = navDropTrigger.closest('.nav-dropdown');
      wrap?.classList.toggle('open');
      navDropTrigger.setAttribute('aria-expanded', String(wrap?.classList.contains('open')));
    }
  }); $$('.nav a').forEach(a=>a.addEventListener('click',()=>{ if(a.classList.contains('nav-drop-trigger') && window.matchMedia('(max-width: 980px)').matches) return; document.body.classList.remove('menu-open'); }));
  const canvas=$('#mesh'), ctx=canvas.getContext('2d');let w,h,dpr,pts=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);w=canvas.width=innerWidth*dpr;h=canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';pts=Array.from({length:Math.min(60,Math.floor(innerWidth/18))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.25*dpr,vy:(Math.random()-.5)*.25*dpr,r:(Math.random()*1.8+1)*dpr}));}function draw(){ctx.clearRect(0,0,w,h);const light=document.documentElement.dataset.theme==='light';const g=ctx.createRadialGradient(w*.5,h*.2,0,w*.5,h*.25,Math.max(w,h)*.7);g.addColorStop(0,light?'rgba(14,165,233,.13)':'rgba(59,130,246,.14)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);pts.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.fillStyle=light?'rgba(21,40,74,.16)':'rgba(255,255,255,.18)';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();for(let j=i+1;j<pts.length;j++){const q=pts[j],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<115*dpr){ctx.strokeStyle=light?`rgba(14,165,233,${(1-d/(115*dpr))*.055})`:`rgba(56,189,248,${(1-d/(115*dpr))*.065})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}});requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize,{passive:true});
  addEventListener('pointermove',e=>{const c=$('.cursor');if(c){c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';}}, {passive:true});
  if(typeof gsap==='undefined')return; gsap.registerPlugin(ScrollTrigger); gsap.defaults({ease:'power3.out'});
  gsap.timeline().to('.loader-line span',{x:'165%',duration:.75,ease:'power2.inOut'}).to('.loader',{yPercent:-100,duration:.75,ease:'expo.inOut'}).set('.loader',{display:'none'}).from('.header',{y:-50,opacity:0,duration:.7},'-=.45').from('.detail-badge,.detail-title,.detail-lede,.detail-actions',{y:36,opacity:0,stagger:.1,duration:.8},'-=.35').from('.detail-device',{scale:.72,rotationY:-28,opacity:0,duration:1,ease:'back.out(1.5)'},'-=.6');
  gsap.to('.detail-rings i',{rotation:360,duration:18,repeat:-1,ease:'none',stagger:2}); gsap.to('.detail-device',{y:-18,rotationY:7,duration:4,repeat:-1,yoyo:true,ease:'sine.inOut'});
  gsap.utils.toArray('.detail-card,.flow-panel,.tag-cloud span,.detail-faq details,.detail-next a').forEach((el,i)=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 84%'},y:45,opacity:0,duration:.75,delay:(i%3)*.04}));
  $$('.depth-card,.detail-card,.detail-next a').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;gsap.to(card,{rotationY:x*10,rotationX:-y*8,transformPerspective:900,duration:.28});});card.addEventListener('pointerleave',()=>gsap.to(card,{rotationY:0,rotationX:0,duration:.55,ease:'elastic.out(1,.45)'}));});
  $$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();gsap.to(el,{x:(e.clientX-r.left-r.width/2)*.18,y:(e.clientY-r.top-r.height/2)*.18,duration:.25});});el.addEventListener('pointerleave',()=>gsap.to(el,{x:0,y:0,duration:.45,ease:'elastic.out(1,.45)'}));});
})();
